# Generated by Django 4.1.4 on 2022-12-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VechicleInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_name', models.CharField(max_length=30)),
                ('Sum_Assurance', models.IntegerField()),
                ('Premium', models.IntegerField()),
                ('Tenure', models.IntegerField()),
            ],
        ),
    ]
