# Generated by Django 4.1.4 on 2022-12-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0002_vechicleinsurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VechicleInsurance',
        ),
    ]
