# Generated by Django 4.1.4 on 2023-01-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0006_vehiclemodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='owner',
        ),
    ]
