# Generated by Django 4.1.4 on 2023-01-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0007_remove_vehiclemodel_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
