# Generated by Django 4.1.4 on 2023-01-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0009_vehiclemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='owner',
            new_name='holder',
        ),
    ]
