# Generated by Django 4.1.4 on 2023-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0010_rename_owner_vehiclemodel_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=50)),
                ('card', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry', models.DateField()),
            ],
        ),
    ]
