# Generated by Django 4.1.4 on 2023-01-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0011_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
