# Generated by Django 4.1.4 on 2023-01-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0013_vehiclemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='usermodel',
        ),
        migrations.DeleteModel(
            name='VechicleInsurance',
        ),
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
