# Generated by Django 4.1.4 on 2023-01-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0015_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('cpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
