# Generated by Django 4.1.4 on 2023-01-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0017_quesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='answer',
        ),
    ]
