# Generated by Django 4.1.4 on 2023-01-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0018_remove_quesmodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=50),
        ),
    ]
