# Generated by Django 4.1.4 on 2023-01-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0019_alter_quesmodel_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quesmodel',
        ),
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
