# Generated by Django 4.1.4 on 2023-01-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0023_vehiclemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
