# Generated by Django 4.1.4 on 2023-01-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0025_vehiclemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
