# Generated by Django 4.1.4 on 2023-01-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0027_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
