# Generated by Django 4.1.4 on 2023-01-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0029_payment_vehiclemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry',
            field=models.IntegerField(),
        ),
    ]
