# Generated by Django 4.1.4 on 2023-01-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0030_alter_payment_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
