# Generated by Django 4.1.4 on 2023-01-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0033_alter_vehiclemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='date',
            field=models.DateField(),
        ),
    ]
