# Generated by Django 4.1.4 on 2023-01-11 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0036_alter_vehiclemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='creted_to',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
