# Generated by Django 4.1.4 on 2023-01-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0037_vehiclemodel_creted_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='creted_to',
        ),
    ]
