# Generated by Django 4.1.4 on 2023-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0042_delete_healthinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='healthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=50)),
                ('policy_holder', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('image', models.FileField(upload_to='insapp/static')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('holder_status', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
