# Generated by Django 4.1.4 on 2023-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0043_healthinsurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurance',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
