# Generated by Django 4.1.4 on 2023-01-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0044_alter_healthinsurance_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='healthInsurance',
        ),
    ]
