# Generated by Django 4.1.4 on 2023-01-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0045_delete_healthinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='healthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=50)),
                ('policy_holder', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('image', models.FileField(upload_to='insapp/static')),
            ],
        ),
    ]
