# Generated by Django 4.1.4 on 2023-01-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0046_healthinsurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='healthInsurance',
        ),
    ]
