# Generated by Django 4.1.4 on 2023-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0048_healthinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='homeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='insapp/static')),
            ],
        ),
        migrations.DeleteModel(
            name='healthInsurance',
        ),
    ]
