# Generated by Django 4.1.4 on 2023-01-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0049_homeform_homein_delete_healthinsurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homeform',
        ),
    ]
