# Generated by Django 4.1.4 on 2023-01-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0051_healthinsurance_delete_homein'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
