# Generated by Django 4.1.4 on 2023-01-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0053_vehiclemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='date',
            field=models.DateField(),
        ),
    ]
