# Generated by Django 4.1.4 on 2023-01-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0056_alter_healthinsurance_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
