# Generated by Django 4.1.4 on 2023-01-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0059_lifeinsurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lifeInsurance',
        ),
    ]
