# Generated by Django 4.1.4 on 2023-01-23 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0061_lifeinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeinsurance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
