# Generated by Django 4.1.4 on 2023-01-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0063_helathpayment_lifepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lifeInsurance',
        ),
        migrations.DeleteModel(
            name='lifepayment',
        ),
    ]
