# Generated by Django 4.1.4 on 2023-01-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0065_lifeinsurance_lifepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VechicleInsurance',
        ),
    ]
