# Generated by Django 4.1.4 on 2023-01-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0066_delete_vechicleinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='VechicleInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_name', models.CharField(max_length=30)),
                ('Sum_Assurance', models.IntegerField()),
                ('Premium', models.IntegerField()),
                ('Tenure', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
