# Generated by Django 4.1.4 on 2023-01-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0068_healthinsmodel_lifeinsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='healthInsurance',
        ),
        migrations.DeleteModel(
            name='helathpayment',
        ),
        migrations.DeleteModel(
            name='lifeInsurance',
        ),
        migrations.DeleteModel(
            name='lifepayment',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='vehicleModel',
        ),
    ]
